apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-customer
  namespace: msa
spec:
  stripPrefix:
    prefixes:
      - "/customer"

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-vendor
  namespace: msa
spec:
  stripPrefix:
    prefixes:
      - "/vendor"

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-api
  namespace: msa
spec:
  stripPrefix:
    prefixes:
      - "/api"

